include:
  - board: nice_nano//zmk
    shield: lily58_central dongle_display
    artifact-name: lily58_central_display

  - board: nice_nano//zmk
    shield: lily58_left nice_view
    artifact-name: lily58_left
    
  - board: nice_nano//zmk
    shield: lily58_right nice_view
    artifact-name: lily58_right

#  - board: nice_nano//zmk
#    shield: lily58_central
#    artifact-name: lily58_central
  
#  - board: nice_nano//zmk
#    shield: lily58_left
#    artifact-name: lily58_left
    
#  - board: nice_nano//zmk
#    shield: lily58_right
#    artifact-name: lily58_right
 
  - board: nice_nano//zmk
    shield: settings_reset
