include:
# Klor without dongle 不带dongle的Klor
  # Klor with 0.96oled display(with nice_oled module) 适用于带0.96寸oled的Klor
  - board: nice_nano_v2 
    shield: Klor_left oled096 
    snippet: studio-rpc-usb-uart 
    artifact-name: Klor_left_oled 
  - board: nice_nano_v2
    shield: Klor_right oled096 
    artifact-name: Klor_right_oled
  # Klor with nice!view display(with nice_view_custom module) 适用于带nice_view的Klor
  - board: nice_nano_v2
    shield: Klor_left Nice_view_config nice_view_custom
    snippet: studio-rpc-usb-uart
    artifact-name: Klor_left_nice_view
  - board: nice_nano_v2
    shield: Klor_right Nice_view_config nice_view_custom
    artifact-name: Klor_right_nice_view
  # Klor with vista508 display 适用于带vista508的Klor
  - board: nice_nano_v2
    shield: Klor_left vista508
    snippet: studio-rpc-usb-uart
    artifact-name: Klor_left_vista508
  - board: nice_nano_v2
    shield: Klor_right vista508
    artifact-name: Klor_right_vista508

#Klor with dongle 带dongle的Klor
  # dongle with LCD display 带LCD显示的dongle
  - board: nice_nano_v2
    shield: Klor_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Klor_central_dongle
  # peripheral with 0.96oled display(with nice_oled module) 适用于带0.96寸oled的Klor
  - board: nice_nano_v2
    shield: Klor_dongle_left oled096 
    artifact-name: Klor_peripheral_left_oled
  - board: nice_nano_v2
    shield: Klor_dongle_right oled096 
    artifact-name: Klor_peripheral_right_oled   
  # peripheral with nice!view display(with nice_view_custom module) 适用于带nice_view的Klor
  - board: nice_nano_v2
    shield: Klor_dongle_left Nice_view_config nice_view_custom
    artifact-name: Klor_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Klor_dongle_right Nice_view_config nice_view_custom
    artifact-name: Klor_peripheral_right_nice_view
   # peripheral with vista508 display 适用于带nice_view的Klor
  - board: nice_nano_v2
    shield: Klor_dongle_left vista508
    artifact-name: Klor_peripheral_left_vista508
  - board: nice_nano_v2
    shield: Klor_dongle_right vista508
    artifact-name: Klor_peripheral_right_vista508

  - board: nice_nano_v2
    shield: settings_reset