#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#
# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
#Display:LCD configs
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n 
#Zmk studio configs
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
#Other configs
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y