#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#

# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="PandaKB_Lily58"

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Bluetooth LE(블루투스 저전력) 전송 출력(Tx Power)을 최대치인 +8 dBm으로 설정
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y

CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=n
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=n
CONFIG_LV_Z_VDB_SIZE=32

#화면 항상켜기
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=0
